---
title: "gt-themes"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(gt)
library(gtTemplates)
library(tidyverse)
```

```{r}
mtcars |> 
  gt() |> 
  gt_theme_simple()
```


```{r}
metric_cols <- us_migration |> 
  select(matches("^m_")) |> 
  names()

pct_cols <- us_migration |> 
  select(matches("^pct_")) |> 
  names()

print(metric_cols)
print(pct_cols)

us_migration |> 
  gt() |>
  gt_theme_simple() |> 
  fmt_number(
    columns = any_of(metric_cols),
    decimals = 0
  ) |> 
  fmt_percent(
    columns = any_of(pct_cols),
    decimals = 0
  )
```


```{r}
us_migration |> 
  gt() |> 
  gt_default_formatting() |> 
  gt_theme_simple()
```


### Campaign Data with Summary at Bottom

```{r}
metric_cols <- campaign |> 
  select(spend, impressions, clicks) |> 
  names()

pct_cols <- campaign |> 
  select(ctr) |> 
  names()

cp_cols <- campaign |> 
  select(cpc) |> 
  names()



campaign |> 
gt() |> 
  gt_default_formatting() |>
  gt_theme_simple() |>
  grand_summary_rows(fns = list(summary = ~ sum(.)), columns = metric_cols) |> 
  grand_summary_rows(fns = list(summary = ~ sum(clicks) /  sum(impressions) ), columns = pct_cols) |> 
  grand_summary_rows(fns = list(summary = ~ sum(spend) /  sum(clicks) ), columns = cp_cols) 
```


